#!/usr/bin/env bash
# ============================
# filesystem_kernel_harden.sh
# CyberPatriot-style Filesystem & Kernel Hardening
# ============================

set -o errexit
set -o nounset
set -o pipefail

# -------------------------
# Configuration
# -------------------------
STAMP="$(date +%Y%m%d-%H%M%S)"
LOGFILE="/var/log/fs_kernel_harden_${STAMP}.log"
UNDO_FILE="/root/fs_kernel_harden_undo_${STAMP}.sh"

# Files & directories to backup
SUDOERS="/etc/sudoers"
SYSCTL_CONF="/etc/sysctl.conf"
TMP_DIRS=("/tmp" "/var/tmp")
SECURE_DIRS=("/etc" "/bin" "/sbin" "/usr/bin" "/usr/sbin")

# -------------------------
# Logging & helpers
# -------------------------
log() {
    local ts; ts="$(date --iso-8601=seconds 2>/dev/null || date)"
    echo "[$ts] $*"
}

append_undo() {
    echo "$1" >> "$UNDO_FILE"
}

ensure_root() {
    [[ "${EUID:-0}" -eq 0 ]] || { echo "[-] Must run as root"; exit 1; }
}

safe_backup() {
    for f in "$@"; do
        [[ -f "$f" ]] || continue
        cp -p "$f" "${f}.bak.${STAMP}"
        append_undo "cp -f '${f}.bak.${STAMP}' '$f' || true"
        log "[+] Backed up $f"
    done
}

# -------------------------
# Main Execution
# -------------------------
ensure_root

# Initialize undo file
cat > "$UNDO_FILE" <<'EOF'
#!/usr/bin/env bash
set -e
# Undo commands generated by filesystem_kernel_harden.sh
EOF
chmod 700 "$UNDO_FILE"

# Logging
exec > >(tee -a "$LOGFILE") 2>&1
log "[*] Starting Filesystem & Kernel Hardening (STAMP=$STAMP)"

# -------------------------
# Sudoers hardening
# -------------------------
log "[*] Hardening /etc/sudoers"
safe_backup "$SUDOERS"
chmod 440 "$SUDOERS"
append_undo "chmod 440 '$SUDOERS' || true"
visudo -cf "$SUDOERS" || { log "[-] Sudoers syntax error"; exit 1; }

# -------------------------
# Secure directories
# -------------------------
log "[*] Securing sensitive directories"
for d in "${SECURE_DIRS[@]}"; do
    [[ -d "$d" ]] || continue
    chmod -R go-rwx "$d" || true
    append_undo "echo 'Manual restore needed for $d permissions'"
done

# -------------------------
# /tmp and /var/tmp hardening
# -------------------------
log "[*] Hardening /tmp and /var/tmp"
for t in "${TMP_DIRS[@]}"; do
    chmod 1777 "$t"
    append_undo "chmod 1777 '$t' || true"
done

# -------------------------
# Kernel parameters (sysctl)
# -------------------------
log "[*] Hardening kernel parameters"
safe_backup "$SYSCTL_CONF"

cat >> "$SYSCTL_CONF" <<'EOF'
# CyberPatriot security sysctl settings
# IP Spoofing protection
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
# Ignore ICMP broadcasts
net.ipv4.icmp_echo_ignore_broadcasts = 1
# Enable TCP SYN cookies
net.ipv4.tcp_syncookies = 1
# Log martian packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
# Disable IP forwarding
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0
# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
EOF

sysctl -p || true
append_undo "cp -f '${SYSCTL_CONF}.bak.${STAMP}' '$SYSCTL_CONF' && sysctl -p || true"

# -------------------------
# Completed
# -------------------------
log "[+] Filesystem & Kernel Hardening Completed"
log "[+] Undo file created: $UNDO_FILE"

exit 0
