#!/usr/bin/env bash
# ============================
# logging_harden.sh
# CyberPatriot-style Logging & Monitoring Hardening
# ============================

set -o errexit
set -o nounset
set -o pipefail

# -------------------------
# Configuration
# -------------------------
STAMP="$(date +%Y%m%d-%H%M%S)"
LOGFILE="/var/log/logging_harden_${STAMP}.log"
UNDO_FILE="/root/logging_harden_undo_${STAMP}.sh"

# Files to backup/edit
RSYSLOG_CONF="/etc/rsyslog.conf"
AUDITD_CONF="/etc/audit/auditd.conf"
FAIL2BAN_CONF_DIR="/etc/fail2ban"
LOGROTATE_CONF="/etc/logrotate.conf"

# Packages to install
REQUIRED_PKGS=(rsyslog auditd fail2ban logrotate)

# -------------------------
# Logging & helpers
# -------------------------
log() {
    local ts; ts="$(date --iso-8601=seconds 2>/dev/null || date)"
    echo "[$ts] $*"
}

append_undo() {
    echo "$1" >> "$UNDO_FILE"
}

ensure_root() {
    [[ "${EUID:-0}" -eq 0 ]] || { echo "[-] Must run as root"; exit 1; }
}

safe_backup() {
    for f in "$@"; do
        [[ -f "$f" ]] || continue
        cp -p "$f" "${f}.bak.${STAMP}"
        append_undo "cp -f '${f}.bak.${STAMP}' '$f' || true"
        log "[+] Backed up $f"
    done
}

pkg_installed() {
    dpkg-query -W -f='${Status} ${Package}\n' "$1" 2>/dev/null | grep -q "^install ok installed"
}

# -------------------------
# Main Execution
# -------------------------
ensure_root

# Initialize undo file
cat > "$UNDO_FILE" <<'EOF'
#!/usr/bin/env bash
set -e
# Undo commands generated by logging_harden.sh
EOF
chmod 700 "$UNDO_FILE"

# Logging
exec > >(tee -a "$LOGFILE") 2>&1
log "[*] Starting Logging & Monitoring Hardening (STAMP=$STAMP)"

# -------------------------
# Install required packages
# -------------------------
log "[*] Installing required packages"
apt-get update || true
for pkg in "${REQUIRED_PKGS[@]}"; do
    if pkg_installed "$pkg"; then
        log "[=] $pkg already installed"
    else
        DEBIAN_FRONTEND=noninteractive apt-get -y install "$pkg" || log "[-] Failed to install $pkg"
        append_undo "apt-get -y purge '$pkg' || true"
    fi
done

# -------------------------
# Rsyslog Hardening
# -------------------------
log "[*] Hardening Rsyslog"
safe_backup "$RSYSLOG_CONF"
sed -i -E 's/^#?\$FileCreateMode.*/$FileCreateMode 0640/' "$RSYSLOG_CONF"
sed -i -E 's/^#?\$DirCreateMode.*/$DirCreateMode 0750/' "$RSYSLOG_CONF"
systemctl restart rsyslog || true
append_undo "cp -f '${RSYSLOG_CONF}.bak.${STAMP}' '$RSYSLOG_CONF' && systemctl restart rsyslog || true"

# -------------------------
# Auditd Hardening
# -------------------------
log "[*] Hardening Auditd"
safe_backup "$AUDITD_CONF"
sed -i -E 's/^#?max_log_file.*/max_log_file = 10/' "$AUDITD_CONF"
sed -i -E 's/^#?max_log_file_action.*/max_log_file_action = ROTATE/' "$AUDITD_CONF"
sed -i -E 's/^#?space_left_action.*/space_left_action = EMAIL/' "$AUDITD_CONF"
systemctl enable --now auditd || true
append_undo "cp -f '${AUDITD_CONF}.bak.${STAMP}' '$AUDITD_CONF' && systemctl restart auditd || true"

# -------------------------
# Fail2Ban Hardening
# -------------------------
log "[*] Hardening Fail2Ban"
for j in "${FAIL2BAN_CONF_DIR}"/*.conf; do
    safe_backup "$j"
done

# Configure default ban parameters
if [[ -f "${FAIL2BAN_CONF_DIR}/jail.local" ]]; then
    safe_backup "${FAIL2BAN_CONF_DIR}/jail.local"
else
    touch "${FAIL2BAN_CONF_DIR}/jail.local"
fi

cat > "${FAIL2BAN_CONF_DIR}/jail.local" <<'EOF'
[DEFAULT]
bantime = 1800
findtime = 600
maxretry = 5
backend = systemd
EOF

systemctl enable --now fail2ban || true
append_undo "echo 'Manual undo may be required for fail2ban configuration'"

# -------------------------
# Logrotate Hardening
# -------------------------
log "[*] Hardening Logrotate"
safe_backup "$LOGROTATE_CONF"
sed -i -E 's/^#?compress.*/compress/' "$LOGROTATE_CONF"
sed -i -E 's/^#?create.*/create 0640 root adm/' "$LOGROTATE_CONF"
append_undo "cp -f '${LOGROTATE_CONF}.bak.${STAMP}' '$LOGROTATE_CONF' || true"

# -------------------------
# Completed
# -------------------------
log "[+] Logging & Monitoring Hardening Completed"
log "[+] Undo file created: $UNDO_FILE"

