#!/usr/bin/env bash
# ============================
# cp_harden_network_services.sh
# CyberPatriot Network & Service Hardening
# Fully applied (no dry-run)
# ============================

set -o errexit
set -o nounset
set -o pipefail

# -------------------------
# Configuration
# -------------------------
STAMP="$(date +%Y%m%d-%H%M%S)"
LOGFILE="/var/log/cp_net_harden_${STAMP}.log"
UNDO_FILE="/root/cp_net_undo_${STAMP}.sh"
ROLLBACK="/root/restore_cp_net_${STAMP}.sh"

# Required packages
REQUIRED_PKGS=(ufw fail2ban apache2 nginx)

# Unnecessary services to disable
DISABLE_SERVICES=(ftp telnet samba rpcbind nfs)

# Protected users (skip locking)
PROTECTED_USERS=()

# -------------------------
# Logging helpers
# -------------------------
log() {
    local ts; ts="$(date --iso-8601=seconds 2>/dev/null || date)"
    echo "[$ts] $*"
}

run() {
    log "EXEC: $*"
    "$@"
}

pkg_installed() {
    dpkg-query -W -f='${Status} ${Package}\n' "$1" 2>/dev/null | grep -q "^install ok installed" || return 1
}

append_undo() {
    echo "$1" >> "$UNDO_FILE"
}

ensure_root() {
    [[ "${EUID:-0}" -eq 0 ]] || { echo "[-] Must run as root"; exit 1; }
}

# -------------------------
# Start main execution
# -------------------------
ensure_root

# Initialize undo file
cat > "$UNDO_FILE" <<'EOF'
#!/usr/bin/env bash
set -e
# Undo commands generated by cp_harden_network_services.sh
EOF
chmod 700 "$UNDO_FILE"

# Logging
exec > >(tee -a "$LOGFILE") 2>&1
log "[*] Starting Network & Service Hardening (STAMP=$STAMP)"

# -------------------------
# Install required packages
# -------------------------
log "[*] Installing required packages"
run apt-get update || true
for pkg in "${REQUIRED_PKGS[@]}"; do
    if pkg_installed "$pkg"; then
        log "[=] $pkg already installed"
    else
        DEBIAN_FRONTEND=noninteractive apt-get -y install "$pkg" || log "[-] Failed to install $pkg"
        append_undo "apt-get -y purge '$pkg' || true"
    fi
done

# -------------------------
# Disable unnecessary services
# -------------------------
log "[*] Disabling unnecessary services"
for svc in "${DISABLE_SERVICES[@]}"; do
    if systemctl list-unit-files | grep -q "^${svc}.service"; then
        run systemctl stop "$svc" || true
        run systemctl disable "$svc" || true
        append_undo "systemctl enable --now '$svc' || true"
        log "[+] Disabled $svc"
    else
        log "[=] Service $svc not installed"
    fi
done

# -------------------------
# SSH Hardening
# -------------------------
SSH_CONF="/etc/ssh/sshd_config"
safe_backup() {
    [[ -f "$1" ]] || return
    cp -p "$1" "$1.bak.${STAMP}"
    append_undo "cp -f '$1.bak.${STAMP}' '$1' || true"
}

log "[*] Hardening SSH"
safe_backup "$SSH_CONF"
sed -i -E 's/^#?PermitRootLogin.*/PermitRootLogin no/' "$SSH_CONF"
sed -i -E 's/^#?PasswordAuthentication.*/PasswordAuthentication yes/' "$SSH_CONF"
sed -i -E 's/^#?Protocol.*/Protocol 2/' "$SSH_CONF"
sed -i -E 's/^#?X11Forwarding.*/X11Forwarding no/' "$SSH_CONF"
sed -i -E 's/^#?PermitEmptyPasswords.*/PermitEmptyPasswords no/' "$SSH_CONF"
append_undo "systemctl restart ssh || true"
run systemctl restart ssh

# -------------------------
# Apache/Nginx Hardening
# -------------------------
log "[*] Hardening Apache"
if pkg_installed "apache2"; then
    APACHE_CONF="/etc/apache2/apache2.conf"
    safe_backup "$APACHE_CONF"
    sed -i -E 's/^#?ServerTokens.*/ServerTokens Prod/' "$APACHE_CONF"
    sed -i -E 's/^#?ServerSignature.*/ServerSignature Off/' "$APACHE_CONF"
    sed -i -E 's/^#?TraceEnable.*/TraceEnable Off/' "$APACHE_CONF"
    append_undo "systemctl restart apache2 || true"
    run systemctl restart apache2
else
    log "[=] Apache not installed"
fi

log "[*] Hardening Nginx"
if pkg_installed "nginx"; then
    NGINX_CONF="/etc/nginx/nginx.conf"
    safe_backup "$NGINX_CONF"
    sed -i -E 's/^\s*server_tokens\s+on;/    server_tokens off;/' "$NGINX_CONF" || true
    append_undo "systemctl restart nginx || true"
    run systemctl restart nginx
else
    log "[=] Nginx not installed"
fi

# -------------------------
# UFW firewall configuration
# -------------------------
log "[*] Configuring firewall"
run ufw default deny incoming
run ufw default allow outgoing
run ufw allow OpenSSH
run ufw --force enable
append_undo "ufw --force reset || true"

# -------------------------
# Fail2Ban setup
# -------------------------
log "[*] Configuring Fail2Ban"
FAIL2BAN_CONF="/etc/fail2ban/jail.local"
if [[ ! -f "$FAIL2BAN_CONF" ]]; then
    cp /etc/fail2ban/jail.conf "$FAIL2BAN_CONF"
fi
safe_backup "$FAIL2BAN_CONF"
sed -i -E 's/^#?bantime.*/bantime = 1800/' "$FAIL2BAN_CONF"
sed -i -E 's/^#?maxretry.*/maxretry = 5/' "$FAIL2BAN_CONF"
run systemctl enable --now fail2ban

# -------------------------
# Rollback helper
# -------------------------
cat > "$ROLLBACK" <<EOF
#!/usr/bin/env bash
set -e
# Restore network/service backups and undo commands
[[ -f "${UNDO_FILE}" ]] && /bin/bash "${UNDO_FILE}" || true
echo "[*] Network & Service Hardening rollback completed"
EOF
chmod +x "$ROLLBACK"
log "[+] Rollback helper created: $ROLLBACK"
log "[+] Undo file: $UNDO_FILE"

log "[+] Completed Network & Service Hardening"

exit 0
