#!/usr/bin/env bash
# ============================
# network_services_harden.sh
# CyberPatriot Network & Service Hardening
# Fully Fixed, CP-safe Version
# ============================

set -o errexit
set -o nounset
set -o pipefail

# -------------------------
# Configuration
# -------------------------
STAMP="$(date +%Y%m%d-%H%M%S)"
LOGFILE="/var/log/cp_net_harden_${STAMP}.log"
UNDO_FILE="/root/cp_net_undo_${STAMP}.sh"
ROLLBACK="/root/restore_cp_net_${STAMP}.sh"

# Risky packages/services to purge
RISKY_PKGS=(apache2 nginx ftp telnet samba rpcbind nfs john hydra nmap zenmap metasploit-framework wireshark sqlmap aircrack-ng)
DISABLE_SERVICES=(ftp telnet samba rpcbind nfs apache2 nginx)

# SSH and firewall
SSH_CONF="/etc/ssh/sshd_config"
SSH_PORT=22

# Fail2Ban
FAIL2BAN_CONF="/etc/fail2ban/jail.local"

# -------------------------
# Logging helpers
# -------------------------
log() {
    local ts; ts="$(date --iso-8601=seconds 2>/dev/null || date)"
    echo "[$ts] $*"
}

run() {
    log "EXEC: $*"
    "$@"
}

pkg_installed() {
    dpkg-query -W -f='${Status} ${Package}\n' "$1" 2>/dev/null | grep -q "^install ok installed"
}

append_undo() {
    echo "$1" >> "$UNDO_FILE"
}

ensure_root() {
    [[ "${EUID:-0}" -eq 0 ]] || { echo "[-] Must run as root"; exit 1; }
}

safe_backup() {
    for f in "$@"; do
        [[ -f "$f" ]] || continue
        cp -p "$f" "${f}.bak.${STAMP}"
        append_undo "cp -f '${f}.bak.${STAMP}' '$f' || true"
        log "[+] Backed up $f"
    done
}

# -------------------------
# Main Execution
# -------------------------
ensure_root

# Initialize undo file
cat > "$UNDO_FILE" <<'EOF'
#!/usr/bin/env bash
set -e
# Undo commands generated by network_services_harden.sh
EOF
chmod 700 "$UNDO_FILE"

exec > >(tee -a "$LOGFILE") 2>&1
log "[*] Starting Network & Service Hardening (STAMP=$STAMP)"

# -------------------------
# Stop & disable risky services
# -------------------------
log "[*] Disabling unnecessary/risky services"
for svc in "${DISABLE_SERVICES[@]}"; do
    if systemctl list-unit-files | grep -q "^${svc}\.service"; then
        run systemctl stop "$svc" || true
        run systemctl disable "$svc" || true
        append_undo "systemctl enable --now '$svc' || true"
        log "[+] Disabled $svc"
    else
        log "[=] Service $svc not installed"
    fi
done

# -------------------------
# Purge risky packages
# -------------------------
log "[*] Purging risky packages/tools"
for pkg in "${RISKY_PKGS[@]}"; do
    if pkg_installed "$pkg"; then
        run apt-get -y purge "$pkg" || log "[-] Failed to purge $pkg"
        append_undo "apt-get -y install --no-install-recommends '$pkg' || true"
        log "[+] Purged $pkg"
    else
        log "[=] $pkg not installed"
    fi
done

run apt-get -y autoremove || true
append_undo "apt-get -y install --no-install-recommends ${RISKY_PKGS[*]} || true"

# -------------------------
# SSH Hardening
# -------------------------
if [[ -f "$SSH_CONF" ]]; then
    log "[*] Hardening SSH"
    safe_backup "$SSH_CONF"
    sed -i -E 's/^#?PermitRootLogin.*/PermitRootLogin no/' "$SSH_CONF"
    sed -i -E 's/^#?PasswordAuthentication.*/PasswordAuthentication yes/' "$SSH_CONF"
    sed -i -E 's/^#?Protocol.*/Protocol 2/' "$SSH_CONF"
    sed -i -E 's/^#?X11Forwarding.*/X11Forwarding no/' "$SSH_CONF"
    sed -i -E 's/^#?PermitEmptyPasswords.*/PermitEmptyPasswords no/' "$SSH_CONF"
    run systemctl restart ssh || systemctl restart sshd || true
fi

# -------------------------
# UFW Firewall Hardening
# -------------------------
log "[*] Configuring firewall (UFW)"
run ufw default deny incoming
run ufw default allow outgoing
run ufw allow "$SSH_PORT"
run ufw --force enable
append_undo "ufw --force reset || true"

# -------------------------
# Fail2Ban Hardening
# -------------------------
log "[*] Configuring Fail2Ban"
if [[ -f /etc/fail2ban/jail.conf && ! -f "$FAIL2BAN_CONF" ]]; then
    cp /etc/fail2ban/jail.conf "$FAIL2BAN_CONF"
fi

if [[ -f "$FAIL2BAN_CONF" ]]; then
    safe_backup "$FAIL2BAN_CONF"
    cat > "$FAIL2BAN_CONF" <<'EOF'
[DEFAULT]
bantime = 1800
findtime = 600
maxretry = 5
backend = systemd
EOF
    run systemctl enable --now fail2ban || true
    append_undo "echo 'Manual undo may be required for Fail2Ban configuration'"
fi

# -------------------------
# Rollback helper
# -------------------------
cat > "$ROLLBACK" <<EOF
#!/usr/bin/env bash
set -e
# Restore network/service backups and undo commands
[[ -f "${UNDO_FILE}" ]] && /bin/bash "${UNDO_FILE}" || true
echo "[*] Network & Service Hardening rollback completed"
EOF
chmod +x "$ROLLBACK"
log "[+] Rollback helper created: $ROLLBACK"
log "[+] Undo file: $UNDO_FILE"

log "[+] Completed Network & Service Hardening"
