#!/usr/bin/env bash
# ============================
# cp_harden_network_services_purge.sh
# CyberPatriot Network & Service Hardening
# Purges risky services and tools, applies security hardening
# ============================

set -o errexit
set -o nounset
set -o pipefail

# -------------------------
# Configuration
# -------------------------
STAMP="$(date +%Y%m%d-%H%M%S)"
LOGFILE="/var/log/cp_net_harden_${STAMP}.log"
UNDO_FILE="/root/cp_net_undo_${STAMP}.sh"
ROLLBACK="/root/restore_cp_net_${STAMP}.sh"

# Potentially risky packages to remove
RISKY_PKGS=(
    apache2 nginx ftp telnet samba rpcbind nfs
    john hydra nmap zenmap metasploit-framework wireshark sqlmap aircrack-ng
)

# Services to stop & disable
DISABLE_SERVICES=(ftp telnet samba rpcbind nfs apache2 nginx)

# -------------------------
# Logging helpers
# -------------------------
log() {
    local ts; ts="$(date --iso-8601=seconds 2>/dev/null || date)"
    echo "[$ts] $*"
}

run() {
    log "EXEC: $*"
    "$@"
}

pkg_installed() {
    dpkg-query -W -f='${Status} ${Package}\n' "$1" 2>/dev/null | grep -q "^install ok installed" || return 1
}

append_undo() {
    echo "$1" >> "$UNDO_FILE"
}

ensure_root() {
    [[ "${EUID:-0}" -eq 0 ]] || { echo "[-] Must run as root"; exit 1; }
}

# -------------------------
# Start main execution
# -------------------------
ensure_root

# Initialize undo file
cat > "$UNDO_FILE" <<'EOF'
#!/usr/bin/env bash
set -e
# Undo commands generated by cp_harden_network_services_purge.sh
EOF
chmod 700 "$UNDO_FILE"

# Logging
exec > >(tee -a "$LOGFILE") 2>&1
log "[*] Starting Network & Service Purge & Hardening (STAMP=$STAMP)"

# -------------------------
# Stop & disable risky services
# -------------------------
log "[*] Disabling unnecessary/risky services"
for svc in "${DISABLE_SERVICES[@]}"; do
    if systemctl list-unit-files | grep -q "^${svc}.service"; then
        run systemctl stop "$svc" || true
        run systemctl disable "$svc" || true
        append_undo "systemctl enable --now '$svc' || true"
        log "[+] Disabled $svc"
    else
        log "[=] Service $svc not installed"
    fi
done

# -------------------------
# Purge risky packages
# -------------------------
log "[*] Purging risky/hacking tools"
for pkg in "${RISKY_PKGS[@]}"; do
    if pkg_installed "$pkg"; then
        run apt-get -y purge "$pkg" || log "[-] Failed to purge $pkg"
        append_undo "apt-get -y install --no-install-recommends '$pkg' || true"
        log "[+] Purged $pkg"
    else
        log "[=] $pkg not installed"
    fi
done

run apt-get -y autoremove || true
append_undo "apt-get -y install --no-install-recommends ${RISKY_PKGS[*]} || true"

# -------------------------
# SSH Hardening
# -------------------------
SSH_CONF="/etc/ssh/sshd_config"
if [[ -f "$SSH_CONF" ]]; then
    log "[*] Hardening SSH"
    cp -p "$SSH_CONF" "$SSH_CONF.bak.${STAMP}"
    append_undo "cp -f '$SSH_CONF.bak.${STAMP}' '$SSH_CONF' || true"

    sed -i -E 's/^#?PermitRootLogin.*/PermitRootLogin no/' "$SSH_CONF"
    sed -i -E 's/^#?PasswordAuthentication.*/PasswordAuthentication yes/' "$SSH_CONF"
    sed -i -E 's/^#?Protocol.*/Protocol 2/' "$SSH_CONF"
    sed -i -E 's/^#?X11Forwarding.*/X11Forwarding no/' "$SSH_CONF"
    sed -i -E 's/^#?PermitEmptyPasswords.*/PermitEmptyPasswords no/' "$SSH_CONF"

    run systemctl restart ssh || true
fi

# -------------------------
# UFW Firewall Hardening
# -------------------------
log "[*] Configuring firewall (UFW)"
run ufw default deny incoming
run ufw default allow outgoing
run ufw allow OpenSSH
run ufw --force enable
append_undo "ufw --force reset || true"

# -------------------------
# Fail2Ban Hardening
# -------------------------
log "[*] Configuring Fail2Ban"
FAIL2BAN_CONF="/etc/fail2ban/jail.local"
if [[ -f /etc/fail2ban/jail.conf && ! -f "$FAIL2BAN_CONF" ]]; then
    cp /etc/fail2ban/jail.conf "$FAIL2BAN_CONF"
fi

if [[ -f "$FAIL2BAN_CONF" ]]; then
    cp -p "$FAIL2BAN_CONF" "$FAIL2BAN_CONF.bak.${STAMP}"
    append_undo "cp -f '$FAIL2BAN_CONF.bak.${STAMP}' '$FAIL2BAN_CONF' || true"

    sed -i -E 's/^#?bantime.*/bantime = 1800/' "$FAIL2BAN_CONF"
    sed -i -E 's/^#?maxretry.*/maxretry = 5/' "$FAIL2BAN_CONF"
    run systemctl enable --now fail2ban || true
fi

# -------------------------
# Rollback helper
# -------------------------
cat > "$ROLLBACK" <<EOF
#!/usr/bin/env bash
set -e
# Restore network/service backups and undo commands
[[ -f "${UNDO_FILE}" ]] && /bin/bash "${UNDO_FILE}" || true
echo "[*] Network & Service Hardening rollback completed"
EOF
chmod +x "$ROLLBACK"
log "[+] Rollback helper created: $ROLLBACK"
log "[+] Undo file: $UNDO_FILE"

log "[+] Completed Network & Service Purge & Hardening"
