#!/usr/bin/env bash
# ============================
# packages_services_harden.sh
# CyberPatriot-style Package & Service Hardening
# ============================

set -o errexit
set -o nounset
set -o pipefail

# -------------------------
# Configuration
# -------------------------
STAMP="$(date +%Y%m%d-%H%M%S)"
LOGFILE="/var/log/packages_services_harden_${STAMP}.log"
UNDO_FILE="/root/packages_services_harden_undo_${STAMP}.sh"

# Prohibited packages (hacking tools)
PROHIBITED_TOOLS=(john hydra nmap zenmap metasploit-framework wireshark sqlmap aircrack-ng)

# Services to secure
SERVICES_TO_ENABLE=(ssh ufw unattended-upgrades)
SERVICES_TO_DISABLE=(telnet ftp vsftpd apache2 mysql)

# Firewall rules
SSH_PORT=22

# -------------------------
# Logging & helpers
# -------------------------
log() {
    local ts; ts="$(date --iso-8601=seconds 2>/dev/null || date)"
    echo "[$ts] $*"
}

append_undo() {
    echo "$1" >> "$UNDO_FILE"
}

ensure_root() {
    [[ "${EUID:-0}" -eq 0 ]] || { echo "[-] Must run as root"; exit 1; }
}

pkg_installed() {
    dpkg-query -W -f='${Status} ${Package}\n' "$1" 2>/dev/null | grep -q "^install ok installed" || return 1
}

safe_purge_pkg() {
    local pkg="$1"
    if pkg_installed "$pkg"; then
        apt-get -y purge "$pkg" && log "[+] Purged $pkg"
        append_undo "apt-get -y install '$pkg' || true"
    else
        log "[=] $pkg not installed"
    fi
}

safe_install_pkg() {
    local pkg="$1"
    if ! pkg_installed "$pkg"; then
        DEBIAN_FRONTEND=noninteractive apt-get -y install "$pkg"
        log "[+] Installed $pkg"
        append_undo "apt-get -y purge '$pkg' || true"
    else
        log "[=] $pkg already installed"
    fi
}

# -------------------------
# Main execution
# -------------------------
ensure_root

# Initialize undo file
cat > "$UNDO_FILE" <<'EOF'
#!/usr/bin/env bash
set -e
# Undo commands generated by packages_services_harden.sh
EOF
chmod 700 "$UNDO_FILE"

# Logging
exec > >(tee -a "$LOGFILE") 2>&1
log "[*] Starting Package & Service Hardening (STAMP=$STAMP)"

# -------------------------
# Remove prohibited packages
# -------------------------
log "[*] Removing prohibited hacking tools"
for t in "${PROHIBITED_TOOLS[@]}"; do
    safe_purge_pkg "$t"
done
apt-get -y autoremove
append_undo "apt-get -y install --no-install-recommends ${PROHIBITED_TOOLS[*]} || true"

# -------------------------
# Install & secure essential packages
# -------------------------
log "[*] Installing essential security packages"
for pkg in "${SERVICES_TO_ENABLE[@]}"; do
    safe_install_pkg "$pkg"
done

# -------------------------
# Enable & configure services
# -------------------------
log "[*] Enabling & starting essential services"
for s in "${SERVICES_TO_ENABLE[@]}"; do
    if systemctl list-unit-files | grep -q "^${s}\.service"; then
        systemctl enable --now "$s"
        log "[+] Enabled & started $s"
        append_undo "systemctl disable --now '$s' || true"
    fi
done

# -------------------------
# Disable & stop dangerous/unneeded services
# -------------------------
log "[*] Disabling & stopping unnecessary/dangerous services"
for s in "${SERVICES_TO_DISABLE[@]}"; do
    if systemctl list-unit-files | grep -q "^${s}\.service"; then
        systemctl disable --now "$s"
        log "[+] Disabled & stopped $s"
        append_undo "systemctl enable --now '$s' || true"
    fi
done

# -------------------------
# SSH hardening
# -------------------------
SSH_CONF="/etc/ssh/sshd_config"
safe_backup "$SSH_CONF"
log "[*] Hardening SSH configuration"
sed -i -E 's/^#?PermitRootLogin.*/PermitRootLogin no/' "$SSH_CONF"
sed -i -E 's/^#?PasswordAuthentication.*/PasswordAuthentication yes/' "$SSH_CONF"
sed -i -E 's/^#?X11Forwarding.*/X11Forwarding no/' "$SSH_CONF"
systemctl restart ssh || systemctl restart sshd || true
append_undo "cp -f '${SSH_CONF}.bak.${STAMP}' '$SSH_CONF' && systemctl restart ssh || systemctl restart sshd || true"

# -------------------------
# UFW Firewall configuration
# -------------------------
log "[*] Configuring UFW firewall"
ufw allow "$SSH_PORT"
ufw default deny incoming
ufw default allow outgoing
ufw --force enable
append_undo "ufw --force disable || true"

# -------------------------
# Unattended upgrades configuration
# -------------------------
APT_10="/etc/apt/apt.conf.d/10periodic"
APT_20="/etc/apt/apt.conf.d/20auto-upgrades"
APT_50="/etc/apt/apt.conf.d/50unattended-upgrades"
safe_backup "$APT_10" "$APT_20" "$APT_50"

cat > "$APT_10" <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
EOF

cat > "$APT_20" <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF

if [[ -f "$APT_50" ]]; then
    sed -i -E 's#^//\s*Unattended-Upgrade::Remove-Unused-Kernel-Packages.*#Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";#' "$APT_50" || true
    sed -i -E 's#^//\s*Unattended-Upgrade::Remove-Unused-Dependencies.*#Unattended-Upgrade::Remove-Unused-Dependencies "true";#' "$APT_50" || true
    append_undo "cp -f '${APT_50}.bak.${STAMP}' '${APT_50}' || true"
fi

systemctl enable --now unattended-upgrades.service || true

log "[+] Package & Service Hardening Completed"
log "[+] Undo file created: $UNDO_FILE"

exit 0
