#!/usr/bin/env bash
# ============================
# services_harden.sh
# CyberPatriot-style Service/Daemon Hardening
# Fully Fixed, Competition-Safe Version
# ============================

set -o errexit
set -o nounset
set -o pipefail

# -------------------------
# Configuration
# -------------------------
STAMP="$(date +%Y%m%d-%H%M%S)"
LOGFILE="/var/log/services_harden_${STAMP}.log"
UNDO_FILE="/root/services_harden_undo_${STAMP}.sh"

SERVICES_TO_DISABLE=(apache2 ftp vsftpd nfs-server rpcbind samba telnet dovecot)

SSH_CONF="/etc/ssh/sshd_config"
APACHE_CONF="/etc/apache2/apache2.conf"
FTP_CONF="/etc/vsftpd.conf"

# -------------------------
# Logging & helpers
# -------------------------
log() {
    local ts; ts="$(date --iso-8601=seconds 2>/dev/null || date)"
    echo "[$ts] $*"
}

append_undo() {
    echo "$1" >> "$UNDO_FILE"
}

ensure_root() {
    [[ "${EUID:-0}" -eq 0 ]] || { echo "[-] Must run as root"; exit 1; }
}

safe_backup() {
    for f in "$@"; do
        [[ -f "$f" ]] || continue
        cp -p "$f" "${f}.bak.${STAMP}"
        append_undo "cp -f '${f}.bak.${STAMP}' '$f' || true"
        log "[+] Backed up $f"
    done
}

pkg_installed() {
    dpkg-query -W -f='${Status} ${Package}\n' "$1" 2>/dev/null | grep -q "^install ok installed"
}

# -------------------------
# Main execution
# -------------------------
ensure_root

# Initialize undo file
cat > "$UNDO_FILE" <<'EOF'
#!/usr/bin/env bash
set -e
# Undo commands generated by services_harden.sh
EOF
chmod 700 "$UNDO_FILE"

# Logging
exec > >(tee -a "$LOGFILE") 2>&1
log "[*] Starting Service/Daemon Hardening (STAMP=$STAMP)"

# -------------------------
# SSH Hardening
# -------------------------
log "[*] Hardening SSH"
if [[ -f "$SSH_CONF" ]]; then
    safe_backup "$SSH_CONF"
    sed -i -E 's/^#?PermitRootLogin.*/PermitRootLogin no/' "$SSH_CONF"
    sed -i -E 's/^#?PasswordAuthentication.*/PasswordAuthentication yes/' "$SSH_CONF"
    sed -i -E 's/^#?PermitEmptyPasswords.*/PermitEmptyPasswords no/' "$SSH_CONF"
    sed -i -E 's/^#?X11Forwarding.*/X11Forwarding no/' "$SSH_CONF"
    systemctl restart ssh || systemctl restart sshd || true
    append_undo "cp -f '${SSH_CONF}.bak.${STAMP}' '$SSH_CONF' && systemctl restart ssh || systemctl restart sshd || true"
fi

# -------------------------
# Apache Hardening
# -------------------------
if pkg_installed apache2; then
    log "[*] Hardening Apache"
    safe_backup "$APACHE_CONF"
    sed -i -E 's/^#?ServerTokens.*/ServerTokens Prod/' "$APACHE_CONF"
    sed -i -E 's/^#?ServerSignature.*/ServerSignature Off/' "$APACHE_CONF"
    sed -i -E 's/^#?TraceEnable.*/TraceEnable Off/' "$APACHE_CONF"
    systemctl restart apache2 || true
    append_undo "cp -f '${APACHE_CONF}.bak.${STAMP}' '$APACHE_CONF' && systemctl restart apache2 || true"
else
    log "[=] Apache not installed"
fi

# -------------------------
# FTP Hardening
# -------------------------
if pkg_installed vsftpd; then
    log "[*] Hardening FTP"
    safe_backup "$FTP_CONF"
    sed -i -E 's/^#?anonymous_enable.*/anonymous_enable=NO/' "$FTP_CONF"
    sed -i -E 's/^#?local_enable.*/local_enable=YES/' "$FTP_CONF"
    sed -i -E 's/^#?write_enable.*/write_enable=YES/' "$FTP_CONF"
    systemctl restart vsftpd || true
    append_undo "cp -f '${FTP_CONF}.bak.${STAMP}' '$FTP_CONF' && systemctl restart vsftpd || true"
else
    log "[=] vsftpd not installed"
fi

# -------------------------
# Disable unnecessary services
# -------------------------
log "[*] Disabling unnecessary services"
for s in "${SERVICES_TO_DISABLE[@]}"; do
    if systemctl list-unit-files | grep -q "^${s}\.service"; then
        systemctl stop "$s" || true
        systemctl disable "$s" || true
        append_undo "systemctl enable --now '$s' || true"
        log "[+] Disabled $s"
    fi
done

# -------------------------
# MySQL Hardening
# -------------------------
if pkg_installed mysql-server; then
    log "[*] Hardening MySQL"
    # CP-safe: skip interactive prompts
    mysql_secure_installation <<EOF || true
n
y
y
y
y
EOF
    append_undo "echo 'Manual MySQL undo may be required'"
fi

log "[+] Service/Daemon Hardening Completed"
log "[+] Undo file created: $UNDO_FILE"
