#!/usr/bin/env bash
# ============================
# system_harden.sh
# CyberPatriot-style System Hardening
# ============================

set -o errexit
set -o nounset
set -o pipefail

# -------------------------
# Configuration
# -------------------------
STAMP="$(date +%Y%m%d-%H%M%S)"
LOGFILE="/var/log/system_harden_${STAMP}.log"
UNDO_FILE="/root/system_harden_undo_${STAMP}.sh"

# Critical files to check permissions
CRITICAL_FILES=(
    /etc/passwd
    /etc/shadow
    /etc/group
    /etc/gshadow
    /etc/ssh/sshd_config
    /etc/sudoers
)

# Sysctl hardening parameters
declare -A SYSCTL_PARAMS=(
    ["net.ipv4.ip_forward"]="0"
    ["net.ipv4.conf.all.send_redirects"]="0"
    ["net.ipv4.conf.default.send_redirects"]="0"
    ["net.ipv4.conf.all.accept_redirects"]="0"
    ["net.ipv4.conf.default.accept_redirects"]="0"
    ["net.ipv4.conf.all.accept_source_route"]="0"
    ["net.ipv4.conf.default.accept_source_route"]="0"
    ["net.ipv4.tcp_syncookies"]="1"
    ["net.ipv4.conf.all.log_martians"]="1"
    ["net.ipv4.conf.default.log_martians"]="1"
)

# -------------------------
# Logging & helpers
# -------------------------
log() {
    local ts; ts="$(date --iso-8601=seconds 2>/dev/null || date)"
    echo "[$ts] $*"
}

append_undo() {
    echo "$1" >> "$UNDO_FILE"
}

ensure_root() {
    [[ "${EUID:-0}" -eq 0 ]] || { echo "[-] Must run as root"; exit 1; }
}

safe_backup() {
    for f in "$@"; do
        [[ -f "$f" ]] || continue
        cp -p "$f" "${f}.bak.${STAMP}"
        append_undo "cp -f '${f}.bak.${STAMP}' '$f' || true"
        log "[+] Backed up $f"
    done
}

# -------------------------
# Main execution
# -------------------------
ensure_root

# Initialize undo file
cat > "$UNDO_FILE" <<'EOF'
#!/usr/bin/env bash
set -e
# Undo commands generated by system_harden.sh
EOF
chmod 700 "$UNDO_FILE"

# Logging
exec > >(tee -a "$LOGFILE") 2>&1
log "[*] Starting System Hardening (STAMP=$STAMP)"

# -------------------------
# Critical file permissions
# -------------------------
log "[*] Securing critical file permissions"
for f in "${CRITICAL_FILES[@]}"; do
    [[ -f "$f" ]] || continue
    safe_backup "$f"
    case "$f" in
        /etc/passwd) chmod 644 "$f" ;;
        /etc/shadow|/etc/gshadow) chmod 600 "$f" ;;
        /etc/group) chmod 644 "$f" ;;
        /etc/sudoers) chmod 440 "$f" ;;
        /etc/ssh/sshd_config) chmod 600 "$f" ;;
    esac
    log "[+] Set permissions on $f"
done

# -------------------------
# Cron hardening
# -------------------------
log "[*] Restricting cron and at access"
touch /etc/cron.allow /etc/at.allow
chmod 600 /etc/cron.allow /etc/at.allow
> /etc/cron.allow
> /etc/at.allow
touch /etc/cron.deny /etc/at.deny
chmod 600 /etc/cron.deny /etc/at.deny
> /etc/cron.deny
> /etc/at.deny
append_undo "echo 'Manual restore may be required for cron/at allow/deny files'"

# -------------------------
# Sysctl kernel hardening
# -------------------------
log "[*] Applying kernel sysctl hardening"
SYSCTL_CONF="/etc/sysctl.d/99-cyberpatriot.conf"
safe_backup "$SYSCTL_CONF"
for key in "${!SYSCTL_PARAMS[@]}"; do
    val="${SYSCTL_PARAMS[$key]}"
    grep -q "^$key" "$SYSCTL_CONF" 2>/dev/null && sed -i -E "s|^$key.*|$key = $val|" "$SYSCTL_CONF" || echo "$key = $val" >> "$SYSCTL_CONF"
done
sysctl --system
append_undo "cp -f '${SYSCTL_CONF}.bak.${STAMP}' '$SYSCTL_CONF' && sysctl --system || true"

# -------------------------
# Logging & auditing
# -------------------------
log "[*] Installing and configuring auditd"
apt-get -y install auditd audispd-plugins || true
systemctl enable --now auditd.service
append_undo "apt-get -y purge auditd audispd-plugins || true; systemctl disable --now auditd || true"

AUDIT_RULES="/etc/audit/rules.d/cyberpatriot.rules"
safe_backup "$AUDIT_RULES"

cat > "$AUDIT_RULES" <<EOF
# CyberPatriot audit rules
-w /etc/passwd -p wa -k passwd_changes
-w /etc/shadow -p wa -k shadow_changes
-w /etc/group -p wa -k group_changes
-w /etc/gshadow -p wa -k gshadow_changes
-w /etc/sudoers -p wa -k sudoers_changes
-w /etc/ssh/sshd_config -p wa -k sshd_changes
-w /var/log/ -p wa -k log_monitoring
EOF

systemctl restart auditd
append_undo "cp -f '${AUDIT_RULES}.bak.${STAMP}' '$AUDIT_RULES' && systemctl restart auditd || true"

# -------------------------
# Log permissions
# -------------------------
log "[*] Securing log directories"
chmod -R 600 /var/log || true
append_undo "echo 'Manual restore may be needed for /var/log permissions'"

log "[+] System Hardening Completed"
log "[+] Undo file created: $UNDO_FILE"

