#!/usr/bin/env bash
# ============================
# users_harden.sh
# CyberPatriot-style User & Account Hardening
# Fully Fixed, Competition-Safe Version
# ============================

set -o errexit
set -o nounset
set -o pipefail

# -------------------------
# Configuration
# -------------------------
STAMP="$(date +%Y%m%d-%H%M%S)"
LOGFILE="/var/log/users_harden_${STAMP}.log"
UNDO_FILE="/root/users_harden_undo_${STAMP}.sh"

PROTECTED_USERS=("root" "sysadmin")       # Add any manually protected accounts
AUTHORIZED_ADMINS=("admin")               # Must be non-root admins
AUTHORIZED_USERS=("student1" "student2")  # Normal users allowed

LOCK_UID_MIN=1000
FAILED_ATTEMPTS=5
UNLOCK_TIME=1800        # 30 minutes

# -------------------------
# Logging & helpers
# -------------------------
log() {
    local ts; ts="$(date --iso-8601=seconds 2>/dev/null || date)"
    echo "[$ts] $*"
}

append_undo() {
    echo "$1" >> "$UNDO_FILE"
}

ensure_root() {
    [[ "${EUID:-0}" -eq 0 ]] || { echo "[-] Must run as root"; exit 1; }
}

safe_backup() {
    for file in "$@"; do
        [[ -f "$file" ]] || continue
        cp -p "$file" "${file}.bak.${STAMP}"
        append_undo "cp -f '${file}.bak.${STAMP}' '${file}' || true"
        log "[+] Backed up $file"
    done
}

lock_account_safe() {
    local user="$1"
    if [[ " ${PROTECTED_USERS[*]} " == *" $user "* ]]; then
        log "[*] Skipping protected user $user"
        return
    fi
    if id "$user" >/dev/null 2>&1; then
        usermod -L "$user" && log "[+] Locked account $user"
        append_undo "usermod -U '$user' || true"
    fi
}

# -------------------------
# Main execution
# -------------------------
ensure_root

# Initialize undo file
cat > "$UNDO_FILE" <<'EOF'
#!/usr/bin/env bash
set -e
# Undo commands generated by users_harden.sh
EOF
chmod 700 "$UNDO_FILE"

# Logging
exec > >(tee -a "$LOGFILE") 2>&1
log "[*] Starting User & Account Hardening (STAMP=$STAMP)"

# Backup critical files
safe_backup /etc/passwd /etc/shadow /etc/group /etc/login.defs /etc/pam.d/common-auth /etc/pam.d/common-password

# -------------------------
# Ensure authorized admins
# -------------------------
for a in "${AUTHORIZED_ADMINS[@]}"; do
    if ! id "$a" >/dev/null 2>&1; then
        useradd -m -s /bin/bash "$a"
        log "[+] Created admin user $a"
        append_undo "userdel -r '$a' || true"
    fi
    getent group sudo >/dev/null 2>&1 || groupadd sudo
    usermod -aG sudo "$a"
    append_undo "deluser '$a' sudo || true"
done

# -------------------------
# Ensure authorized normal users
# -------------------------
for u in "${AUTHORIZED_USERS[@]}"; do
    if ! id "$u" >/dev/null 2>&1; then
        useradd -m -s /bin/bash "$u"
        log "[+] Created user $u"
        append_undo "userdel -r '$u' || true"
    fi
    deluser "$u" sudo || true
    append_undo "usermod -aG sudo '$u' || true"
done

# -------------------------
# Lock unauthorized users (UID >= LOCK_UID_MIN)
# -------------------------
while IFS=: read -r name _ uid _; do
    [[ "$uid" -lt "$LOCK_UID_MIN" ]] && continue
    [[ " ${AUTHORIZED_ADMINS[*]} ${AUTHORIZED_USERS[*]} ${PROTECTED_USERS[*]} " == *" $name "* ]] && continue
    [[ "$name" == "nobody" ]] && continue
    lock_account_safe "$name"
done < /etc/passwd

# -------------------------
# PAM password policy enforcement
# -------------------------
log "[*] Enforcing PAM faillock (deny=${FAILED_ATTEMPTS}, unlock=${UNLOCK_TIME}s)"
safe_backup /etc/pam.d/common-auth
grep -q "pam_faillock.so preauth" /etc/pam.d/common-auth || sed -i "1i auth required pam_faillock.so preauth silent deny=${FAILED_ATTEMPTS} unlock_time=${UNLOCK_TIME}" /etc/pam.d/common-auth
grep -q "pam_faillock.so authfail" /etc/pam.d/common-auth || echo "auth [default=die] pam_faillock.so authfail deny=${FAILED_ATTEMPTS} unlock_time=${UNLOCK_TIME}" >> /etc/pam.d/common-auth
append_undo "cp -f /etc/pam.d/common-auth.bak.${STAMP} /etc/pam.d/common-auth || true"

# -------------------------
# Expire passwords for all users to force change on first login
# -------------------------
log "[*] Expiring passwords for non-protected users"
while IFS=: read -r name _ uid _; do
    [[ "$uid" -lt "$LOCK_UID_MIN" ]] && continue
    [[ " ${PROTECTED_USERS[*]} ${AUTHORIZED_ADMINS[*]} " == *" $name "* ]] && continue
    passwd -e "$name" && log "[+] Expired password for $name"
done < /etc/passwd

log "[+] User & Account Hardening Completed"
log "[+] Undo file created: $UNDO_FILE"
